# Generated by Django 4.2 on 2024-02-04 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, null=True)),
                ('apellidos', models.CharField(max_length=250, null=True)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Debe de ingresar los 8 digitos de DNI', regex='^\\+?1?\\d{8}')])),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
