# Generated by Django 4.2 on 2024-02-06 15:44

import autoslug.fields
import datetime
import django.core.validators
from django.db import migrations, models
import persona.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, null=True)),
                ('apellidos', models.CharField(max_length=250, null=True)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Debe de ingresar los 8 digitos de DNI', regex='^\\+?1?\\d{8}')])),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('curso', models.CharField(max_length=255, unique=True)),
                ('n_certificado', models.CharField(max_length=5, null=True, verbose_name='N° Certificado')),
                ('fecha_emision', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de Emision')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=persona.models.concatenar_cert_uuid, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
